name: file_preview_example
description: Demonstrates how to use the file_preview plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_preview:
    path: ../

#  file_preview:
#    git:
#      url: https://github.com/gstory0404/file_preview.git
#      ref: 592a52839861075a3da9200fada10667c1cb68da

  cupertino_icons: ^1.0.2
  file_picker: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/file_ceshi.docx
